# Generated by Django 3.1.3 on 2022-02-10 12:50

import Wallet.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('token', models.CharField(default=Wallet.models.hex_uuid, max_length=36)),
                ('owner', models.CharField(max_length=36)),
                ('status', models.IntegerField(choices=[(0, 'enabled'), (1, 'disabled')], default=0)),
                ('enabled_at', models.DateTimeField(null=True)),
                ('disabled_at', models.DateTimeField(null=True)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
