# Generated by Django 3.1.3 on 2022-02-10 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
