# Generated by Django 3.1.3 on 2022-02-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_auto_20220210_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(max_length=36),
        ),
    ]
