# Generated by Django 3.1.3 on 2022-02-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_auto_20220210_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=36)),
                ('deposited_at', models.DateTimeField(null=True)),
                ('withdrawn_at', models.DateTimeField(null=True)),
                ('amount', models.IntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='Wallet.wallet')),
            ],
        ),
    ]
